ADDRESS: "0.0.0.0"
PORT: '50051'
CURRENCY_GRPC_ADDRESS: "localhost:50053"
BLOCKCHAIN_GW_ADDRESS: "localhost:50051"
TRANSACTIONS_GW_ADDRESS: "localhost:50055"
BLOCKCHAIN_GW_TIMEOUT: 5  # seconds
CURRENCIES_GW_TIMEOUT: 5 # seconds
TRANSACTIONS_GW_TIMEOUT: 5 # seconds
MAIL_DOMAIN: 'mail.bonumchain.com'
MAIL_USERNAME: 'dev@email.bonumchain.com'
ENV: 'local'  # for logs
PROJECT_NAME: 'api-project-206881048866'
LOGGING_LEVEL: 'WARN'
PRINT_TRACEBACK: false
REMOTE_OPERATION_ATTEMPT_NUMBER : 3
DEBUG: true
CELERY_NAMESPACE: 'local'
MONITORING_TEMPLATE: 'monitoring_result.html'
ALARM_TEMPLATE: 'balance_alarm.html'
RECIPIENTS : []
MONITORING_TRANSACTIONS_PERIOD: 5 # minutes
MONITORING_WALLETS_PERIOD: 12 # hours
PGSTRING: 'postgresql:///wallets'
Ethereum: 1000
Bitcoin: 1000
Binance-coin: 1000
TrueUSD: 1000
OmiseGo: 500
Basic-Attention-Token: 500
Holo: 500
Chainlink: 500
Zilliqa: 500
USD-Coin: 1000
