image: registry.gitlab.com/bonum/images/python3-base

stages:
  - test

variables:
  POSTGRES_DB: postgres
  PGDATABASE: postgres
  POSTGRES_USER: postgres
  PGUSER: postgres
  POSTGRES_PASSWORD: testing-password
  PGPASSWORD: testing-password
  POSTGRES_ENABLED: "true"

py.test:
  stage: test
  variables:
    REDIS_HOST: redis
  services:
    - postgres:9.6
    - redis
  script:
    - "echo REDIS_HOST: redis > /etc/config.yaml"
    - pytest -v tests --pg_string="postgresql://postgres:testing-password@postgres/postgres"
  only:
    - master
    - dev
    - stage
