image: registry.gitlab.com/bonum/images/python3-base

stages:
  - test

variables:
  POSTGRES_DB: postgres
  PGDATABASE: postgres
  POSTGRES_USER: postgres
  PGUSER: postgres
  POSTGRES_PASSWORD: testing-password
  PGPASSWORD: testing-password
  POSTGRES_ENABLED: "true"

py.test:
  stage: test
  variables:
    REDIS: redis
  services:
    - postgres:9.6
    - redis
  script:
    - "echo REDIS: redis > /config.yaml"
    - pip3 install -r req/test.txt
    - pytest -v --pg_string="postgresql://postgres:testing-password@postgres/postgres"
