FROM python:3.6
MAINTAINER Konstantin Zavadski <healfy92@gmail.com>

ENV PYTHONUNBUFFERED 1
EXPOSE 50051

RUN export CLOUD_SDK_REPO="cloud-sdk-stretch" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update -y && apt-get install libffi-dev ranger vim google-cloud-sdk -y

RUN mkdir /app
WORKDIR /app
ARG reqs_path=req
ADD $reqs_path /app/req
RUN pip install -r req/requirements.txt
