# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: currencies.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='currencies.proto',
  package='currencies',
  syntax='proto3',
  serialized_options=_b('Z\ncurrencies'),
  serialized_pb=_b('\n\x10\x63urrencies.proto\x12\ncurrencies\x1a\x1fgoogle/protobuf/timestamp.proto\"\x07\n\x05\x45mpty\"X\n\x11\x43urrenciesRequest\x12\x14\n\x0c\x63urrencySlug\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\">\n\x12\x43urrenciesResponse\x12(\n\ncurrencies\x18\x01 \x03(\x0b\x32\x14.currencies.Currency\"\x9d\x02\n\x08\x43urrency\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x66ullname\x18\x03 \x01(\t\x12\x0c\n\x04rate\x18\x04 \x01(\t\x12-\n\x0c\x63oefficients\x18\x05 \x03(\x0b\x32\x17.currencies.Coefficient\x12\x0c\n\x04slug\x18\x06 \x01(\t\x12.\n\x05rates\x18\x07 \x03(\x0b\x32\x1f.currencies.Currency.RatesEntry\x12\x0e\n\x06symbol\x18\x08 \x01(\t\x12,\n\x08\x64\x61tetime\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a,\n\nRatesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb1\x01\n\x0b\x43oefficient\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ys\x18\x02 \x01(\x05\x12\x1e\n\x16\x63ollateral_coefficient\x18\x03 \x01(\t\x12\x1d\n\x15mandatory_coefficient\x18\x04 \x01(\t\x12\x1b\n\x13warning_coefficient\x18\x05 \x01(\t\x12,\n\x08\x64\x61tetime\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\x89\x01\n\x11\x43urrenciesService\x12.\n\x06Health\x12\x11.currencies.Empty\x1a\x11.currencies.Empty\x12\x44\n\x03Get\x12\x1d.currencies.CurrenciesRequest\x1a\x1e.currencies.CurrenciesResponseB\x0cZ\ncurrenciesb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='currencies.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=72,
)


_CURRENCIESREQUEST = _descriptor.Descriptor(
  name='CurrenciesRequest',
  full_name='currencies.CurrenciesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currencySlug', full_name='currencies.CurrenciesRequest.currencySlug', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='currencies.CurrenciesRequest.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=162,
)


_CURRENCIESRESPONSE = _descriptor.Descriptor(
  name='CurrenciesResponse',
  full_name='currencies.CurrenciesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currencies', full_name='currencies.CurrenciesResponse.currencies', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=226,
)


_CURRENCY_RATESENTRY = _descriptor.Descriptor(
  name='RatesEntry',
  full_name='currencies.Currency.RatesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='currencies.Currency.RatesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='currencies.Currency.RatesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=514,
)

_CURRENCY = _descriptor.Descriptor(
  name='Currency',
  full_name='currencies.Currency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='currencies.Currency.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='currencies.Currency.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fullname', full_name='currencies.Currency.fullname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rate', full_name='currencies.Currency.rate', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coefficients', full_name='currencies.Currency.coefficients', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slug', full_name='currencies.Currency.slug', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rates', full_name='currencies.Currency.rates', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='currencies.Currency.symbol', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='currencies.Currency.datetime', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CURRENCY_RATESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=514,
)


_COEFFICIENT = _descriptor.Descriptor(
  name='Coefficient',
  full_name='currencies.Coefficient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='currencies.Coefficient.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='days', full_name='currencies.Coefficient.days', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collateral_coefficient', full_name='currencies.Coefficient.collateral_coefficient', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mandatory_coefficient', full_name='currencies.Coefficient.mandatory_coefficient', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='warning_coefficient', full_name='currencies.Coefficient.warning_coefficient', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='currencies.Coefficient.datetime', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=694,
)

_CURRENCIESREQUEST.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CURRENCIESRESPONSE.fields_by_name['currencies'].message_type = _CURRENCY
_CURRENCY_RATESENTRY.containing_type = _CURRENCY
_CURRENCY.fields_by_name['coefficients'].message_type = _COEFFICIENT
_CURRENCY.fields_by_name['rates'].message_type = _CURRENCY_RATESENTRY
_CURRENCY.fields_by_name['datetime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_COEFFICIENT.fields_by_name['datetime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['CurrenciesRequest'] = _CURRENCIESREQUEST
DESCRIPTOR.message_types_by_name['CurrenciesResponse'] = _CURRENCIESRESPONSE
DESCRIPTOR.message_types_by_name['Currency'] = _CURRENCY
DESCRIPTOR.message_types_by_name['Coefficient'] = _COEFFICIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'currencies_pb2'
  # @@protoc_insertion_point(class_scope:currencies.Empty)
  ))
_sym_db.RegisterMessage(Empty)

CurrenciesRequest = _reflection.GeneratedProtocolMessageType('CurrenciesRequest', (_message.Message,), dict(
  DESCRIPTOR = _CURRENCIESREQUEST,
  __module__ = 'currencies_pb2'
  # @@protoc_insertion_point(class_scope:currencies.CurrenciesRequest)
  ))
_sym_db.RegisterMessage(CurrenciesRequest)

CurrenciesResponse = _reflection.GeneratedProtocolMessageType('CurrenciesResponse', (_message.Message,), dict(
  DESCRIPTOR = _CURRENCIESRESPONSE,
  __module__ = 'currencies_pb2'
  # @@protoc_insertion_point(class_scope:currencies.CurrenciesResponse)
  ))
_sym_db.RegisterMessage(CurrenciesResponse)

Currency = _reflection.GeneratedProtocolMessageType('Currency', (_message.Message,), dict(

  RatesEntry = _reflection.GeneratedProtocolMessageType('RatesEntry', (_message.Message,), dict(
    DESCRIPTOR = _CURRENCY_RATESENTRY,
    __module__ = 'currencies_pb2'
    # @@protoc_insertion_point(class_scope:currencies.Currency.RatesEntry)
    ))
  ,
  DESCRIPTOR = _CURRENCY,
  __module__ = 'currencies_pb2'
  # @@protoc_insertion_point(class_scope:currencies.Currency)
  ))
_sym_db.RegisterMessage(Currency)
_sym_db.RegisterMessage(Currency.RatesEntry)

Coefficient = _reflection.GeneratedProtocolMessageType('Coefficient', (_message.Message,), dict(
  DESCRIPTOR = _COEFFICIENT,
  __module__ = 'currencies_pb2'
  # @@protoc_insertion_point(class_scope:currencies.Coefficient)
  ))
_sym_db.RegisterMessage(Coefficient)


DESCRIPTOR._options = None
_CURRENCY_RATESENTRY._options = None

_CURRENCIESSERVICE = _descriptor.ServiceDescriptor(
  name='CurrenciesService',
  full_name='currencies.CurrenciesService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=697,
  serialized_end=834,
  methods=[
  _descriptor.MethodDescriptor(
    name='Health',
    full_name='currencies.CurrenciesService.Health',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='currencies.CurrenciesService.Get',
    index=1,
    containing_service=None,
    input_type=_CURRENCIESREQUEST,
    output_type=_CURRENCIESRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURRENCIESSERVICE)

DESCRIPTOR.services_by_name['CurrenciesService'] = _CURRENCIESSERVICE

# @@protoc_insertion_point(module_scope)
