# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: wallets.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import google.protobuf.timestamp_pb2
import google.protobuf.duration_pb2
import google.api.annotations_pb2
import protoc_gen_swagger.options.annotations_pb2
import wallets_pb2


class WalletsBase(abc.ABC):

    @abc.abstractmethod
    async def Healthz(self, stream):
        pass

    @abc.abstractmethod
    async def GetWallet(self, stream):
        pass

    @abc.abstractmethod
    async def StartMonitoring(self, stream):
        pass

    @abc.abstractmethod
    async def StopMonitoring(self, stream):
        pass

    def __mapping__(self):
        return {
            '/wallets.Wallets/Healthz': grpclib.const.Handler(
                self.Healthz,
                grpclib.const.Cardinality.UNARY_UNARY,
                wallets_pb2.HealthzRequest,
                wallets_pb2.HealthzResponse,
            ),
            '/wallets.Wallets/GetWallet': grpclib.const.Handler(
                self.GetWallet,
                grpclib.const.Cardinality.UNARY_UNARY,
                wallets_pb2.WalletRequest,
                wallets_pb2.WalletResponse,
            ),
            '/wallets.Wallets/StartMonitoring': grpclib.const.Handler(
                self.StartMonitoring,
                grpclib.const.Cardinality.UNARY_UNARY,
                wallets_pb2.MonitoringRequest,
                wallets_pb2.MonitoringResponse,
            ),
            '/wallets.Wallets/StopMonitoring': grpclib.const.Handler(
                self.StopMonitoring,
                grpclib.const.Cardinality.UNARY_UNARY,
                wallets_pb2.MonitoringRequest,
                wallets_pb2.MonitoringResponse,
            ),
        }


class WalletsStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Healthz = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wallets.Wallets/Healthz',
            wallets_pb2.HealthzRequest,
            wallets_pb2.HealthzResponse,
        )
        self.GetWallet = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wallets.Wallets/GetWallet',
            wallets_pb2.WalletRequest,
            wallets_pb2.WalletResponse,
        )
        self.StartMonitoring = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wallets.Wallets/StartMonitoring',
            wallets_pb2.MonitoringRequest,
            wallets_pb2.MonitoringResponse,
        )
        self.StopMonitoring = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wallets.Wallets/StopMonitoring',
            wallets_pb2.MonitoringRequest,
            wallets_pb2.MonitoringResponse,
        )
