// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallets.proto

package wlt_go

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseStatus int32

const (
	ResponseStatus_NOT_SET         ResponseStatus = 0
	ResponseStatus_SUCCESS         ResponseStatus = 1
	ResponseStatus_ERROR           ResponseStatus = 2
	ResponseStatus_INVALID_REQUEST ResponseStatus = 3
)

var ResponseStatus_name = map[int32]string{
	0: "NOT_SET",
	1: "SUCCESS",
	2: "ERROR",
	3: "INVALID_REQUEST",
}

var ResponseStatus_value = map[string]int32{
	"NOT_SET":         0,
	"SUCCESS":         1,
	"ERROR":           2,
	"INVALID_REQUEST": 3,
}

func (x ResponseStatus) String() string {
	return proto.EnumName(ResponseStatus_name, int32(x))
}

func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{0}
}

type TransferStatus int32

const (
	TransferStatus_UNDEFINED TransferStatus = 0
	TransferStatus_ACTIVE    TransferStatus = 1
	TransferStatus_CONFIRMED TransferStatus = 2
	TransferStatus_FAILED    TransferStatus = 3
)

var TransferStatus_name = map[int32]string{
	0: "UNDEFINED",
	1: "ACTIVE",
	2: "CONFIRMED",
	3: "FAILED",
}

var TransferStatus_value = map[string]int32{
	"UNDEFINED": 0,
	"ACTIVE":    1,
	"CONFIRMED": 2,
	"FAILED":    3,
}

func (x TransferStatus) String() string {
	return proto.EnumName(TransferStatus_name, int32(x))
}

func (TransferStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{1}
}

type ResponseHeader struct {
	Status               ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=wallets.ResponseStatus" json:"status,omitempty"`
	Description          string         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{0}
}

func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (m *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(m, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_NOT_SET
}

func (m *ResponseHeader) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type HealthzRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthzRequest) Reset()         { *m = HealthzRequest{} }
func (m *HealthzRequest) String() string { return proto.CompactTextString(m) }
func (*HealthzRequest) ProtoMessage()    {}
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{1}
}

func (m *HealthzRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthzRequest.Unmarshal(m, b)
}
func (m *HealthzRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthzRequest.Marshal(b, m, deterministic)
}
func (m *HealthzRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthzRequest.Merge(m, src)
}
func (m *HealthzRequest) XXX_Size() int {
	return xxx_messageInfo_HealthzRequest.Size(m)
}
func (m *HealthzRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthzRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthzRequest proto.InternalMessageInfo

type HealthzResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HealthzResponse) Reset()         { *m = HealthzResponse{} }
func (m *HealthzResponse) String() string { return proto.CompactTextString(m) }
func (*HealthzResponse) ProtoMessage()    {}
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{2}
}

func (m *HealthzResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthzResponse.Unmarshal(m, b)
}
func (m *HealthzResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthzResponse.Marshal(b, m, deterministic)
}
func (m *HealthzResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthzResponse.Merge(m, src)
}
func (m *HealthzResponse) XXX_Size() int {
	return xxx_messageInfo_HealthzResponse.Size(m)
}
func (m *HealthzResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthzResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthzResponse proto.InternalMessageInfo

func (m *HealthzResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type Wallet struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CurrencySlug         string   `protobuf:"bytes,2,opt,name=currency_slug,json=currencySlug,proto3" json:"currency_slug,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	IsPlatform           bool     `protobuf:"varint,4,opt,name=is_platform,json=isPlatform,proto3" json:"is_platform,omitempty"`
	ExternalId           int64    `protobuf:"varint,5,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wallet) Reset()         { *m = Wallet{} }
func (m *Wallet) String() string { return proto.CompactTextString(m) }
func (*Wallet) ProtoMessage()    {}
func (*Wallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{3}
}

func (m *Wallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wallet.Unmarshal(m, b)
}
func (m *Wallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wallet.Marshal(b, m, deterministic)
}
func (m *Wallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wallet.Merge(m, src)
}
func (m *Wallet) XXX_Size() int {
	return xxx_messageInfo_Wallet.Size(m)
}
func (m *Wallet) XXX_DiscardUnknown() {
	xxx_messageInfo_Wallet.DiscardUnknown(m)
}

var xxx_messageInfo_Wallet proto.InternalMessageInfo

func (m *Wallet) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Wallet) GetCurrencySlug() string {
	if m != nil {
		return m.CurrencySlug
	}
	return ""
}

func (m *Wallet) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Wallet) GetIsPlatform() bool {
	if m != nil {
		return m.IsPlatform
	}
	return false
}

func (m *Wallet) GetExternalId() int64 {
	if m != nil {
		return m.ExternalId
	}
	return 0
}

type MonitoringRequest struct {
	Wallet               *Wallet  `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitoringRequest) Reset()         { *m = MonitoringRequest{} }
func (m *MonitoringRequest) String() string { return proto.CompactTextString(m) }
func (*MonitoringRequest) ProtoMessage()    {}
func (*MonitoringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{4}
}

func (m *MonitoringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitoringRequest.Unmarshal(m, b)
}
func (m *MonitoringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitoringRequest.Marshal(b, m, deterministic)
}
func (m *MonitoringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitoringRequest.Merge(m, src)
}
func (m *MonitoringRequest) XXX_Size() int {
	return xxx_messageInfo_MonitoringRequest.Size(m)
}
func (m *MonitoringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitoringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MonitoringRequest proto.InternalMessageInfo

func (m *MonitoringRequest) GetWallet() *Wallet {
	if m != nil {
		return m.Wallet
	}
	return nil
}

type MonitoringResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MonitoringResponse) Reset()         { *m = MonitoringResponse{} }
func (m *MonitoringResponse) String() string { return proto.CompactTextString(m) }
func (*MonitoringResponse) ProtoMessage()    {}
func (*MonitoringResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{5}
}

func (m *MonitoringResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitoringResponse.Unmarshal(m, b)
}
func (m *MonitoringResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitoringResponse.Marshal(b, m, deterministic)
}
func (m *MonitoringResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitoringResponse.Merge(m, src)
}
func (m *MonitoringResponse) XXX_Size() int {
	return xxx_messageInfo_MonitoringResponse.Size(m)
}
func (m *MonitoringResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitoringResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MonitoringResponse proto.InternalMessageInfo

func (m *MonitoringResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CheckBalanceRequest struct {
	BodyCurrency         string   `protobuf:"bytes,1,opt,name=body_currency,json=bodyCurrency,proto3" json:"body_currency,omitempty"`
	BodyAmount           string   `protobuf:"bytes,2,opt,name=body_amount,json=bodyAmount,proto3" json:"body_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckBalanceRequest) Reset()         { *m = CheckBalanceRequest{} }
func (m *CheckBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*CheckBalanceRequest) ProtoMessage()    {}
func (*CheckBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{6}
}

func (m *CheckBalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckBalanceRequest.Unmarshal(m, b)
}
func (m *CheckBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckBalanceRequest.Marshal(b, m, deterministic)
}
func (m *CheckBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckBalanceRequest.Merge(m, src)
}
func (m *CheckBalanceRequest) XXX_Size() int {
	return xxx_messageInfo_CheckBalanceRequest.Size(m)
}
func (m *CheckBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckBalanceRequest proto.InternalMessageInfo

func (m *CheckBalanceRequest) GetBodyCurrency() string {
	if m != nil {
		return m.BodyCurrency
	}
	return ""
}

func (m *CheckBalanceRequest) GetBodyAmount() string {
	if m != nil {
		return m.BodyAmount
	}
	return ""
}

type CheckBalanceResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CheckBalanceResponse) Reset()         { *m = CheckBalanceResponse{} }
func (m *CheckBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*CheckBalanceResponse) ProtoMessage()    {}
func (*CheckBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{7}
}

func (m *CheckBalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckBalanceResponse.Unmarshal(m, b)
}
func (m *CheckBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckBalanceResponse.Marshal(b, m, deterministic)
}
func (m *CheckBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckBalanceResponse.Merge(m, src)
}
func (m *CheckBalanceResponse) XXX_Size() int {
	return xxx_messageInfo_CheckBalanceResponse.Size(m)
}
func (m *CheckBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckBalanceResponse proto.InternalMessageInfo

func (m *CheckBalanceResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type Transaction struct {
	From                 string         `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string         `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Hash                 string         `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	WalletId             int64          `protobuf:"varint,4,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Value                string         `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	IsOutput             bool           `protobuf:"varint,6,opt,name=isOutput,proto3" json:"isOutput,omitempty"`
	CurrencySlug         string         `protobuf:"bytes,7,opt,name=currencySlug,proto3" json:"currencySlug,omitempty"`
	TransferStatus       TransferStatus `protobuf:"varint,8,opt,name=transfer_status,json=transferStatus,proto3,enum=wallets.TransferStatus" json:"transfer_status,omitempty"`
	IsFeeTrx             bool           `protobuf:"varint,9,opt,name=is_fee_trx,json=isFeeTrx,proto3" json:"is_fee_trx,omitempty"`
	TimeConfirmed        int64          `protobuf:"varint,10,opt,name=time_confirmed,json=timeConfirmed,proto3" json:"time_confirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{8}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Transaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Transaction) GetWalletId() int64 {
	if m != nil {
		return m.WalletId
	}
	return 0
}

func (m *Transaction) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Transaction) GetIsOutput() bool {
	if m != nil {
		return m.IsOutput
	}
	return false
}

func (m *Transaction) GetCurrencySlug() string {
	if m != nil {
		return m.CurrencySlug
	}
	return ""
}

func (m *Transaction) GetTransferStatus() TransferStatus {
	if m != nil {
		return m.TransferStatus
	}
	return TransferStatus_UNDEFINED
}

func (m *Transaction) GetIsFeeTrx() bool {
	if m != nil {
		return m.IsFeeTrx
	}
	return false
}

func (m *Transaction) GetTimeConfirmed() int64 {
	if m != nil {
		return m.TimeConfirmed
	}
	return 0
}

type TransactionRequest struct {
	Transaction          []*Transaction `protobuf:"bytes,1,rep,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{9}
}

func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (m *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(m, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetTransaction() []*Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type TransactionResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{10}
}

func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionResponse.Unmarshal(m, b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
}
func (m *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(m, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionResponse.Size(m)
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func (m *TransactionResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type InputTransactionsRequest struct {
	WalletId             int64    `protobuf:"varint,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	WalletAddress        string   `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputTransactionsRequest) Reset()         { *m = InputTransactionsRequest{} }
func (m *InputTransactionsRequest) String() string { return proto.CompactTextString(m) }
func (*InputTransactionsRequest) ProtoMessage()    {}
func (*InputTransactionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{11}
}

func (m *InputTransactionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputTransactionsRequest.Unmarshal(m, b)
}
func (m *InputTransactionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputTransactionsRequest.Marshal(b, m, deterministic)
}
func (m *InputTransactionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputTransactionsRequest.Merge(m, src)
}
func (m *InputTransactionsRequest) XXX_Size() int {
	return xxx_messageInfo_InputTransactionsRequest.Size(m)
}
func (m *InputTransactionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InputTransactionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InputTransactionsRequest proto.InternalMessageInfo

func (m *InputTransactionsRequest) GetWalletId() int64 {
	if m != nil {
		return m.WalletId
	}
	return 0
}

func (m *InputTransactionsRequest) GetWalletAddress() string {
	if m != nil {
		return m.WalletAddress
	}
	return ""
}

type InputTransactionsResponse struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Transactions         []*Transaction  `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InputTransactionsResponse) Reset()         { *m = InputTransactionsResponse{} }
func (m *InputTransactionsResponse) String() string { return proto.CompactTextString(m) }
func (*InputTransactionsResponse) ProtoMessage()    {}
func (*InputTransactionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_45d934467f2c3fba, []int{12}
}

func (m *InputTransactionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputTransactionsResponse.Unmarshal(m, b)
}
func (m *InputTransactionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputTransactionsResponse.Marshal(b, m, deterministic)
}
func (m *InputTransactionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputTransactionsResponse.Merge(m, src)
}
func (m *InputTransactionsResponse) XXX_Size() int {
	return xxx_messageInfo_InputTransactionsResponse.Size(m)
}
func (m *InputTransactionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InputTransactionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InputTransactionsResponse proto.InternalMessageInfo

func (m *InputTransactionsResponse) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *InputTransactionsResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterEnum("wallets.ResponseStatus", ResponseStatus_name, ResponseStatus_value)
	proto.RegisterEnum("wallets.TransferStatus", TransferStatus_name, TransferStatus_value)
	proto.RegisterType((*ResponseHeader)(nil), "wallets.ResponseHeader")
	proto.RegisterType((*HealthzRequest)(nil), "wallets.HealthzRequest")
	proto.RegisterType((*HealthzResponse)(nil), "wallets.HealthzResponse")
	proto.RegisterType((*Wallet)(nil), "wallets.Wallet")
	proto.RegisterType((*MonitoringRequest)(nil), "wallets.MonitoringRequest")
	proto.RegisterType((*MonitoringResponse)(nil), "wallets.MonitoringResponse")
	proto.RegisterType((*CheckBalanceRequest)(nil), "wallets.CheckBalanceRequest")
	proto.RegisterType((*CheckBalanceResponse)(nil), "wallets.CheckBalanceResponse")
	proto.RegisterType((*Transaction)(nil), "wallets.Transaction")
	proto.RegisterType((*TransactionRequest)(nil), "wallets.TransactionRequest")
	proto.RegisterType((*TransactionResponse)(nil), "wallets.TransactionResponse")
	proto.RegisterType((*InputTransactionsRequest)(nil), "wallets.InputTransactionsRequest")
	proto.RegisterType((*InputTransactionsResponse)(nil), "wallets.InputTransactionsResponse")
}

func init() { proto.RegisterFile("wallets.proto", fileDescriptor_45d934467f2c3fba) }

var fileDescriptor_45d934467f2c3fba = []byte{
	// 1214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdf, 0x6e, 0x1b, 0x45,
	0x17, 0xef, 0x3a, 0xa9, 0x1d, 0x1f, 0x27, 0x8e, 0x3b, 0xc9, 0xd7, 0x6f, 0x3f, 0x37, 0x5f, 0x3b,
	0xdd, 0xaa, 0x22, 0x04, 0x1a, 0xd3, 0x20, 0x2a, 0x54, 0x71, 0x81, 0xeb, 0x6c, 0x5a, 0xa3, 0x34,
	0x29, 0x6b, 0xa7, 0x48, 0x20, 0x75, 0x35, 0xd9, 0x1d, 0xdb, 0x4b, 0xd7, 0x3b, 0xcb, 0xce, 0x6c,
	0xd3, 0x72, 0x07, 0x42, 0x3c, 0x40, 0xb8, 0xe2, 0x82, 0x27, 0x40, 0x3c, 0x03, 0x4f, 0xc0, 0x45,
	0xc5, 0x2b, 0xf0, 0x1e, 0xa0, 0x99, 0x9d, 0xf5, 0xbf, 0x38, 0x55, 0x15, 0x71, 0x65, 0xcf, 0xf9,
	0xfd, 0xf6, 0xcc, 0xef, 0x77, 0xce, 0xcc, 0xd9, 0x85, 0x95, 0x13, 0x12, 0x86, 0x54, 0xf0, 0xed,
	0x38, 0x61, 0x82, 0xa1, 0x92, 0x5e, 0xd6, 0x6f, 0xf4, 0x19, 0xeb, 0x87, 0xb4, 0xa1, 0xc2, 0xc7,
	0x69, 0xaf, 0x21, 0x82, 0x21, 0xe5, 0x82, 0x0c, 0xe3, 0x8c, 0x59, 0xbf, 0x3e, 0x4b, 0xf0, 0xd3,
	0x84, 0x88, 0x80, 0x45, 0x1a, 0xdf, 0xd0, 0x38, 0x89, 0x83, 0x06, 0x89, 0x22, 0x26, 0x14, 0xa8,
	0xf7, 0xa9, 0xbf, 0xaf, 0x7e, 0xbc, 0x3b, 0x7d, 0x1a, 0xdd, 0xe1, 0x27, 0xa4, 0xdf, 0xa7, 0x49,
	0x83, 0xc5, 0x8a, 0x71, 0x96, 0x6d, 0x79, 0x50, 0x75, 0x28, 0x8f, 0x59, 0xc4, 0xe9, 0x23, 0x4a,
	0x7c, 0x9a, 0xa0, 0x06, 0x14, 0xb9, 0x20, 0x22, 0xe5, 0xa6, 0x81, 0x8d, 0xcd, 0xea, 0xce, 0x7f,
	0xb7, 0x73, 0x1f, 0x39, 0xb1, 0xa3, 0x60, 0x47, 0xd3, 0x10, 0x86, 0x8a, 0x4f, 0xb9, 0x97, 0x04,
	0x6a, 0x13, 0xb3, 0x80, 0x8d, 0xcd, 0xb2, 0x33, 0x19, 0xb2, 0x6a, 0x50, 0x7d, 0x44, 0x49, 0x28,
	0x06, 0xdf, 0x3a, 0xf4, 0x9b, 0x94, 0x72, 0x61, 0x3d, 0x80, 0xd5, 0x51, 0x24, 0x4b, 0x2a, 0xf7,
	0x1d, 0x28, 0x05, 0x6a, 0xdf, 0xca, 0x9c, 0x7d, 0x33, 0x81, 0x8e, 0xa6, 0x59, 0x3f, 0x1b, 0x50,
	0xfc, 0x42, 0x51, 0x50, 0x15, 0x0a, 0x81, 0xaf, 0x9e, 0x5b, 0x70, 0x0a, 0x81, 0x8f, 0x6e, 0xc1,
	0x8a, 0x97, 0x26, 0x09, 0x8d, 0xbc, 0x57, 0x2e, 0x0f, 0xd3, 0xbe, 0x16, 0xb5, 0x9c, 0x07, 0x3b,
	0x61, 0xda, 0x47, 0x26, 0x94, 0x88, 0xef, 0x27, 0x94, 0x73, 0x73, 0x41, 0xc1, 0xf9, 0x12, 0xdd,
	0x80, 0x4a, 0xc0, 0xdd, 0x38, 0x24, 0xa2, 0xc7, 0x92, 0xa1, 0xb9, 0x88, 0x8d, 0xcd, 0x25, 0x07,
	0x02, 0xfe, 0x44, 0x47, 0x24, 0x81, 0xbe, 0x14, 0x34, 0x89, 0x48, 0xe8, 0x06, 0xbe, 0x79, 0x59,
	0x6d, 0x0c, 0x79, 0xa8, 0xed, 0x5b, 0x9f, 0xc0, 0x95, 0xc7, 0x2c, 0x0a, 0x04, 0x4b, 0x82, 0xa8,
	0xaf, 0x4d, 0xa3, 0x77, 0xa0, 0x98, 0x59, 0xd2, 0x0e, 0x57, 0x47, 0x0e, 0x33, 0x1b, 0x8e, 0x86,
	0x2d, 0x1b, 0xd0, 0xe4, 0xd3, 0x17, 0x2d, 0xd0, 0x57, 0xb0, 0xd6, 0x1a, 0x50, 0xef, 0xf9, 0x03,
	0x12, 0x92, 0xc8, 0xa3, 0xb9, 0x8c, 0x5b, 0xb0, 0x72, 0xcc, 0xfc, 0x57, 0x6e, 0x5e, 0x0c, 0x95,
	0xae, 0xec, 0x2c, 0xcb, 0x60, 0x4b, 0xc7, 0xa4, 0x43, 0x45, 0x22, 0x43, 0x96, 0x46, 0x42, 0xd7,
	0x0f, 0x64, 0xa8, 0xa9, 0x22, 0xd6, 0x43, 0x58, 0x9f, 0x4e, 0x7e, 0x51, 0x95, 0xbf, 0x17, 0xa0,
	0xd2, 0x4d, 0x48, 0xc4, 0x89, 0x27, 0x0f, 0x0b, 0x42, 0xb0, 0xd8, 0x4b, 0xd8, 0x50, 0xab, 0x52,
	0xff, 0x65, 0x7f, 0x05, 0xd3, 0x22, 0x0a, 0x82, 0x49, 0xce, 0x80, 0xf0, 0x81, 0xee, 0x9b, 0xfa,
	0x8f, 0xae, 0x41, 0x39, 0xdb, 0x49, 0x76, 0x64, 0x51, 0x75, 0x64, 0x29, 0x0b, 0xb4, 0x7d, 0xb4,
	0x0e, 0x97, 0x5f, 0x90, 0x30, 0xa5, 0xaa, 0x55, 0x65, 0x27, 0x5b, 0xa0, 0x3a, 0x2c, 0x05, 0xfc,
	0x30, 0x15, 0x71, 0x2a, 0xcc, 0xa2, 0x6a, 0xf2, 0x68, 0x8d, 0x2c, 0x98, 0x3a, 0x2d, 0x66, 0x69,
	0xce, 0x09, 0xfa, 0x14, 0x56, 0x85, 0x54, 0xde, 0xa3, 0x89, 0xab, 0xef, 0xcc, 0xd2, 0xcc, 0x9d,
	0xe9, 0x6a, 0x5c, 0xdf, 0x99, 0xaa, 0x98, 0x5a, 0xa3, 0x0d, 0x80, 0x80, 0xbb, 0x3d, 0x4a, 0x5d,
	0x91, 0xbc, 0x34, 0xcb, 0xb9, 0x86, 0x3d, 0x4a, 0xbb, 0xc9, 0x4b, 0x74, 0x1b, 0xaa, 0x72, 0x36,
	0xb8, 0x1e, 0x8b, 0x7a, 0x41, 0x32, 0xa4, 0xbe, 0x09, 0xca, 0xd7, 0x8a, 0x8c, 0xb6, 0xf2, 0xa0,
	0xb5, 0x0f, 0x68, 0xa2, 0x80, 0x79, 0x9b, 0xef, 0x41, 0x45, 0x8c, 0xa3, 0xa6, 0x81, 0x17, 0x36,
	0x2b, 0x3b, 0xeb, 0xd3, 0xc2, 0xf4, 0x13, 0x93, 0x44, 0x6b, 0x0f, 0xd6, 0xa6, 0xb2, 0x5d, 0xb4,
	0xaf, 0xcf, 0xc0, 0x6c, 0x47, 0x71, 0x2a, 0x26, 0x92, 0xf1, 0x5c, 0xdb, 0x54, 0xaf, 0x8c, 0x99,
	0x5e, 0xdd, 0x86, 0xaa, 0x06, 0xf3, 0xeb, 0x99, 0x35, 0x5e, 0xcf, 0xd3, 0x66, 0x16, 0xb4, 0x7e,
	0x34, 0xe0, 0x7f, 0x73, 0x36, 0xb8, 0xa0, 0x5c, 0xf4, 0x31, 0x2c, 0x4f, 0x54, 0x41, 0xee, 0x79,
	0x7e, 0xbd, 0xa6, 0x98, 0x5b, 0x9f, 0x8d, 0x47, 0xa8, 0xee, 0x6a, 0x05, 0x4a, 0x07, 0x87, 0x5d,
	0xb7, 0x63, 0x77, 0x6b, 0x97, 0xe4, 0xa2, 0x73, 0xd4, 0x6a, 0xd9, 0x9d, 0x4e, 0xcd, 0x40, 0x65,
	0xb8, 0x6c, 0x3b, 0xce, 0xa1, 0x53, 0x2b, 0xa0, 0x35, 0x58, 0x6d, 0x1f, 0x3c, 0x6d, 0xee, 0xb7,
	0x77, 0x5d, 0xc7, 0xfe, 0xfc, 0xc8, 0xee, 0x74, 0x6b, 0x0b, 0x5b, 0x7b, 0x50, 0x9d, 0x3e, 0x31,
	0x68, 0x05, 0xca, 0x47, 0x07, 0xbb, 0xf6, 0x5e, 0xfb, 0xc0, 0xde, 0xad, 0x5d, 0x42, 0x00, 0xc5,
	0x66, 0xab, 0xdb, 0x7e, 0x6a, 0xd7, 0x0c, 0x09, 0xb5, 0x0e, 0x0f, 0xf6, 0xda, 0xce, 0x63, 0x7b,
	0xb7, 0x56, 0x90, 0xd0, 0x5e, 0xb3, 0xbd, 0x6f, 0xef, 0xd6, 0x16, 0x76, 0xfe, 0x5e, 0x82, 0x52,
	0x36, 0x54, 0x38, 0xfa, 0xc5, 0x80, 0x92, 0x1e, 0xb6, 0x68, 0x5c, 0x86, 0xe9, 0x81, 0x5c, 0x37,
	0xcf, 0x02, 0x99, 0x25, 0xcb, 0x3d, 0x6d, 0x3e, 0x46, 0x66, 0x16, 0xc5, 0x9e, 0xbc, 0xf2, 0x41,
	0xd4, 0xc7, 0x34, 0xf2, 0x63, 0x16, 0x44, 0xa2, 0x7e, 0xf7, 0x3c, 0x64, 0x1b, 0x3b, 0x54, 0xa4,
	0x49, 0xc4, 0xf1, 0x4c, 0xc6, 0xef, 0xff, 0xfc, 0xeb, 0xa7, 0x42, 0x19, 0x95, 0x1a, 0x03, 0x15,
	0x47, 0xaf, 0x0d, 0x58, 0xed, 0x08, 0x92, 0x88, 0xf1, 0xcc, 0x43, 0xf5, 0x91, 0x9c, 0x33, 0x63,
	0xb4, 0x7e, 0x6d, 0x2e, 0xa6, 0xd5, 0xfe, 0x60, 0x9c, 0x36, 0x29, 0x7a, 0x4f, 0xe5, 0xc3, 0xc3,
	0x11, 0x8e, 0xb3, 0x47, 0x30, 0x8b, 0x30, 0xa7, 0xc9, 0x8b, 0xc0, 0xa3, 0x63, 0x07, 0xf7, 0x3a,
	0x34, 0xf2, 0x73, 0xc2, 0x49, 0x20, 0x06, 0x38, 0x26, 0x09, 0x19, 0x72, 0x2c, 0x18, 0xe6, 0xb3,
	0x79, 0xc6, 0x09, 0x94, 0x8d, 0xab, 0xd6, 0x95, 0x86, 0xe2, 0xb8, 0x63, 0xce, 0x7d, 0x63, 0x0b,
	0xfd, 0x61, 0x40, 0xb5, 0x23, 0x58, 0xfc, 0x6f, 0x58, 0xfa, 0xce, 0x38, 0x6d, 0x7a, 0x68, 0x4b,
	0xa6, 0x7b, 0x4b, 0x47, 0x1f, 0xbd, 0xd1, 0xd1, 0x74, 0x9a, 0x19, 0x43, 0xff, 0xb1, 0x6a, 0x0d,
	0x49, 0x99, 0xf1, 0xf3, 0xab, 0x01, 0xcb, 0x93, 0xe3, 0x1e, 0x6d, 0x8c, 0x14, 0xcf, 0x79, 0xc5,
	0xd4, 0xff, 0x7f, 0x0e, 0xaa, 0x1d, 0x3d, 0x3b, 0x6d, 0xda, 0xe8, 0xa6, 0x82, 0xb0, 0xc6, 0x30,
	0xeb, 0xe1, 0xfc, 0x85, 0x8b, 0xf3, 0x2f, 0x25, 0x9c, 0x51, 0x8e, 0x35, 0xe5, 0x64, 0x40, 0x23,
	0x7c, 0x42, 0x71, 0xc0, 0x79, 0x4a, 0x71, 0xc8, 0x48, 0xa4, 0x24, 0xd7, 0x50, 0xb5, 0xa1, 0x4e,
	0x9f, 0xab, 0x89, 0xe8, 0x37, 0x03, 0xca, 0x47, 0xb1, 0x4f, 0x84, 0x9a, 0xa2, 0xd7, 0xe6, 0xde,
	0x61, 0xad, 0x74, 0x63, 0x3e, 0xa8, 0x85, 0xd2, 0xd3, 0xe6, 0x3e, 0xba, 0x6e, 0xeb, 0xba, 0xca,
	0xf2, 0xa5, 0x2a, 0x2d, 0x9e, 0x18, 0x00, 0xf5, 0xad, 0x6c, 0x2b, 0x9c, 0xbd, 0x01, 0x26, 0x21,
	0x8e, 0xe5, 0xdb, 0x0b, 0x1f, 0x87, 0xcc, 0x7b, 0xee, 0x0d, 0x48, 0xa0, 0xf5, 0x5a, 0x95, 0x46,
	0x96, 0x46, 0x0e, 0x7d, 0x59, 0xdd, 0xd7, 0x06, 0xac, 0x3f, 0xa4, 0xe2, 0xcc, 0x34, 0x43, 0x37,
	0x47, 0xea, 0xce, 0x1b, 0xa5, 0x75, 0xeb, 0x4d, 0x14, 0x6d, 0x23, 0x39, 0x6d, 0x3e, 0x45, 0xef,
	0x4e, 0xda, 0xe8, 0xcb, 0x83, 0x91, 0x9d, 0x8f, 0x40, 0x3e, 0x36, 0xa5, 0xba, 0xfe, 0xf6, 0x54,
	0x65, 0x68, 0xcd, 0xaa, 0x36, 0xfa, 0x72, 0x96, 0x4b, 0x58, 0x7b, 0x7a, 0xf0, 0x44, 0xf6, 0xf8,
	0x2a, 0xac, 0xea, 0x29, 0x94, 0x1f, 0xb2, 0x9d, 0x85, 0xbb, 0xdb, 0x1f, 0x58, 0x8b, 0xf2, 0xdb,
	0x75, 0xcb, 0x30, 0x76, 0x6a, 0x24, 0x8e, 0xc3, 0xc0, 0x53, 0x9f, 0xa4, 0x8d, 0xaf, 0x39, 0x8b,
	0xee, 0x9f, 0x89, 0x7c, 0x59, 0x3c, 0x09, 0xc5, 0x9d, 0x3e, 0x3b, 0x2e, 0xaa, 0x2f, 0xd6, 0x0f,
	0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x44, 0xb5, 0x02, 0x8b, 0x58, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletsClient is the client API for Wallets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletsClient interface {
	Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzResponse, error)
	StartMonitoring(ctx context.Context, in *MonitoringRequest, opts ...grpc.CallOption) (*MonitoringResponse, error)
	StopMonitoring(ctx context.Context, in *MonitoringRequest, opts ...grpc.CallOption) (*MonitoringResponse, error)
	CheckBalance(ctx context.Context, in *CheckBalanceRequest, opts ...grpc.CallOption) (*CheckBalanceResponse, error)
	UpdateTrx(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error)
	GetInputTransactions(ctx context.Context, in *InputTransactionsRequest, opts ...grpc.CallOption) (*InputTransactionsResponse, error)
}

type walletsClient struct {
	cc *grpc.ClientConn
}

func NewWalletsClient(cc *grpc.ClientConn) WalletsClient {
	return &walletsClient{cc}
}

func (c *walletsClient) Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzResponse, error) {
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, "/wallets.Wallets/Healthz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletsClient) StartMonitoring(ctx context.Context, in *MonitoringRequest, opts ...grpc.CallOption) (*MonitoringResponse, error) {
	out := new(MonitoringResponse)
	err := c.cc.Invoke(ctx, "/wallets.Wallets/StartMonitoring", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletsClient) StopMonitoring(ctx context.Context, in *MonitoringRequest, opts ...grpc.CallOption) (*MonitoringResponse, error) {
	out := new(MonitoringResponse)
	err := c.cc.Invoke(ctx, "/wallets.Wallets/StopMonitoring", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletsClient) CheckBalance(ctx context.Context, in *CheckBalanceRequest, opts ...grpc.CallOption) (*CheckBalanceResponse, error) {
	out := new(CheckBalanceResponse)
	err := c.cc.Invoke(ctx, "/wallets.Wallets/CheckBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletsClient) UpdateTrx(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionResponse, error) {
	out := new(TransactionResponse)
	err := c.cc.Invoke(ctx, "/wallets.Wallets/UpdateTrx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletsClient) GetInputTransactions(ctx context.Context, in *InputTransactionsRequest, opts ...grpc.CallOption) (*InputTransactionsResponse, error) {
	out := new(InputTransactionsResponse)
	err := c.cc.Invoke(ctx, "/wallets.Wallets/GetInputTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletsServer is the server API for Wallets service.
type WalletsServer interface {
	Healthz(context.Context, *HealthzRequest) (*HealthzResponse, error)
	StartMonitoring(context.Context, *MonitoringRequest) (*MonitoringResponse, error)
	StopMonitoring(context.Context, *MonitoringRequest) (*MonitoringResponse, error)
	CheckBalance(context.Context, *CheckBalanceRequest) (*CheckBalanceResponse, error)
	UpdateTrx(context.Context, *TransactionRequest) (*TransactionResponse, error)
	GetInputTransactions(context.Context, *InputTransactionsRequest) (*InputTransactionsResponse, error)
}

// UnimplementedWalletsServer can be embedded to have forward compatible implementations.
type UnimplementedWalletsServer struct {
}

func (*UnimplementedWalletsServer) Healthz(ctx context.Context, req *HealthzRequest) (*HealthzResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthz not implemented")
}
func (*UnimplementedWalletsServer) StartMonitoring(ctx context.Context, req *MonitoringRequest) (*MonitoringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMonitoring not implemented")
}
func (*UnimplementedWalletsServer) StopMonitoring(ctx context.Context, req *MonitoringRequest) (*MonitoringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopMonitoring not implemented")
}
func (*UnimplementedWalletsServer) CheckBalance(ctx context.Context, req *CheckBalanceRequest) (*CheckBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBalance not implemented")
}
func (*UnimplementedWalletsServer) UpdateTrx(ctx context.Context, req *TransactionRequest) (*TransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTrx not implemented")
}
func (*UnimplementedWalletsServer) GetInputTransactions(ctx context.Context, req *InputTransactionsRequest) (*InputTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInputTransactions not implemented")
}

func RegisterWalletsServer(s *grpc.Server, srv WalletsServer) {
	s.RegisterService(&_Wallets_serviceDesc, srv)
}

func _Wallets_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthzRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletsServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallets.Wallets/Healthz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletsServer).Healthz(ctx, req.(*HealthzRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallets_StartMonitoring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitoringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletsServer).StartMonitoring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallets.Wallets/StartMonitoring",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletsServer).StartMonitoring(ctx, req.(*MonitoringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallets_StopMonitoring_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonitoringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletsServer).StopMonitoring(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallets.Wallets/StopMonitoring",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletsServer).StopMonitoring(ctx, req.(*MonitoringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallets_CheckBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletsServer).CheckBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallets.Wallets/CheckBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletsServer).CheckBalance(ctx, req.(*CheckBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallets_UpdateTrx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletsServer).UpdateTrx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallets.Wallets/UpdateTrx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletsServer).UpdateTrx(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallets_GetInputTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletsServer).GetInputTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallets.Wallets/GetInputTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletsServer).GetInputTransactions(ctx, req.(*InputTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wallets_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wallets.Wallets",
	HandlerType: (*WalletsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Healthz",
			Handler:    _Wallets_Healthz_Handler,
		},
		{
			MethodName: "StartMonitoring",
			Handler:    _Wallets_StartMonitoring_Handler,
		},
		{
			MethodName: "StopMonitoring",
			Handler:    _Wallets_StopMonitoring_Handler,
		},
		{
			MethodName: "CheckBalance",
			Handler:    _Wallets_CheckBalance_Handler,
		},
		{
			MethodName: "UpdateTrx",
			Handler:    _Wallets_UpdateTrx_Handler,
		},
		{
			MethodName: "GetInputTransactions",
			Handler:    _Wallets_GetInputTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallets.proto",
}
